// Demo/fallback data — used only when the real API (per the REST contract in
// the technical plan) is unreachable, so the frontend stays fully explorable
// during frontend-only development. Shapes mirror the backend collections
// exactly (customers, clusters, plans, recommendations, chatSessions) so
// swapping in the live API requires no UI changes. Operator names here are
// fictional demo brands, not real telecom operators.

export const DEMO_FLAG = true;

export const demoClusters = [
  {
    _id: 'cl_heavy_streamer',
    clusterLabel: 0,
    personaName: 'Heavy-Data Streamer',
    description:
      'Streams video and music constantly, burns through data fast, rarely calls, barely texts.',
    customerCount: 4210,
    centroid: [0.86, 0.18, 0.12, 0.22, 0.15],
    traits: { data: 'Very High', calling: 'Low', sms: 'Low', roaming: 'Low' },
    color: '#22d3ee',
  },
  {
    _id: 'cl_talk_first',
    clusterLabel: 1,
    personaName: 'Talk-First Connector',
    description: 'Lives on voice calls for work and family, modest data use, low roaming.',
    customerCount: 3120,
    centroid: [0.22, 0.88, 0.3, 0.12, 0.1],
    traits: { data: 'Low', calling: 'Very High', sms: 'Medium', roaming: 'Low' },
    color: '#34d399',
  },
  {
    _id: 'cl_global_roamer',
    clusterLabel: 2,
    personaName: 'Global Roamer',
    description: 'Frequently travels abroad, needs reliable roaming and international minutes.',
    customerCount: 980,
    centroid: [0.5, 0.45, 0.2, 0.92, 0.8],
    traits: { data: 'Medium', calling: 'Medium', sms: 'Low', roaming: 'Very High' },
    color: '#fbbf24',
  },
  {
    _id: 'cl_balanced',
    clusterLabel: 3,
    personaName: 'Balanced Everyday User',
    description: 'Steady, moderate use across data, calls and texts — nothing extreme.',
    customerCount: 5460,
    centroid: [0.45, 0.42, 0.4, 0.18, 0.14],
    traits: { data: 'Medium', calling: 'Medium', sms: 'Medium', roaming: 'Low' },
    color: '#60a5fa',
  },
  {
    _id: 'cl_budget_light',
    clusterLabel: 4,
    personaName: 'Budget-Conscious Light User',
    description: 'Minimal usage across the board, highly price sensitive.',
    customerCount: 2870,
    centroid: [0.12, 0.15, 0.18, 0.05, 0.04],
    traits: { data: 'Low', calling: 'Low', sms: 'Low', roaming: 'Very Low' },
    color: '#a78bfa',
  },
];

export const demoOperators = [
  { id: 'nimbus', name: 'Nimbus Mobile', color: '#22d3ee' },
  { id: 'orbit', name: 'Orbit Telecom', color: '#34d399' },
  { id: 'pulse', name: 'Pulse Networks', color: '#fbbf24' },
  { id: 'vantage', name: 'Vantage Mobile', color: '#60a5fa' },
];

export const demoPlans = [
  {
    _id: 'pl_streamer_max',
    planName: 'Streamer Max',
    operator: 'nimbus',
    clusterIds: ['cl_heavy_streamer'],
    price: 899,
    dataGB: 75,
    callMinutes: 300,
    sms: 100,
    roamingIncluded: false,
    validityDays: 30,
    benefits: ['75GB high-speed data', 'Free OTT streaming bundle', 'Nightly data rollover'],
    sourceOperatorRef: 'Nimbus Unlimited Data 75',
  },
  {
    _id: 'pl_streamer_pro',
    planName: 'Streamer Pro',
    operator: 'orbit',
    clusterIds: ['cl_heavy_streamer', 'cl_balanced'],
    price: 649,
    dataGB: 40,
    callMinutes: 400,
    sms: 100,
    roamingIncluded: false,
    validityDays: 28,
    benefits: ['40GB high-speed data', '5G priority access', 'Weekend data boost'],
    sourceOperatorRef: 'Orbit Data Pro 40',
  },
  {
    _id: 'pl_talk_unlimited',
    planName: 'Talk Unlimited',
    operator: 'pulse',
    clusterIds: ['cl_talk_first'],
    price: 399,
    dataGB: 6,
    callMinutes: 3000,
    sms: 1000,
    roamingIncluded: false,
    validityDays: 28,
    benefits: ['Unlimited local + STD calls', '1000 SMS/day', '6GB data'],
    sourceOperatorRef: 'Pulse Talk Plus',
  },
  {
    _id: 'pl_connect_400',
    planName: 'Connect 400',
    operator: 'vantage',
    clusterIds: ['cl_talk_first', 'cl_balanced'],
    price: 299,
    dataGB: 4,
    callMinutes: 1500,
    sms: 300,
    roamingIncluded: false,
    validityDays: 28,
    benefits: ['1500 mins voice', '300 SMS', '4GB data'],
    sourceOperatorRef: 'Vantage Connect 400',
  },
  {
    _id: 'pl_global_traveler',
    planName: 'Global Traveler',
    operator: 'nimbus',
    clusterIds: ['cl_global_roamer'],
    price: 1499,
    dataGB: 20,
    callMinutes: 600,
    sms: 200,
    roamingIncluded: true,
    validityDays: 30,
    benefits: ['International roaming in 90+ countries', '20GB data', 'Discounted intl. calls'],
    sourceOperatorRef: 'Nimbus World Pass',
  },
  {
    _id: 'pl_roam_easy',
    planName: 'Roam Easy',
    operator: 'orbit',
    clusterIds: ['cl_global_roamer', 'cl_balanced'],
    price: 999,
    dataGB: 15,
    callMinutes: 500,
    sms: 150,
    roamingIncluded: true,
    validityDays: 28,
    benefits: ['Roaming in 40+ countries', '15GB data', 'Free incoming calls abroad'],
    sourceOperatorRef: 'Orbit Roam Easy',
  },
  {
    _id: 'pl_everyday_smart',
    planName: 'Everyday Smart',
    operator: 'vantage',
    clusterIds: ['cl_balanced'],
    price: 449,
    dataGB: 20,
    callMinutes: 800,
    sms: 300,
    roamingIncluded: false,
    validityDays: 28,
    benefits: ['20GB data', '800 mins voice', 'Free OTT trial'],
    sourceOperatorRef: 'Vantage Smart 20',
  },
  {
    _id: 'pl_allrounder',
    planName: 'All-Rounder 30',
    operator: 'pulse',
    clusterIds: ['cl_balanced', 'cl_heavy_streamer'],
    price: 549,
    dataGB: 30,
    callMinutes: 1000,
    sms: 300,
    roamingIncluded: false,
    validityDays: 30,
    benefits: ['30GB data', '1000 mins', 'Weekend rollover data'],
    sourceOperatorRef: 'Pulse All-Rounder',
  },
  {
    _id: 'pl_saver_lite',
    planName: 'Saver Lite',
    operator: 'vantage',
    clusterIds: ['cl_budget_light'],
    price: 149,
    dataGB: 2,
    callMinutes: 300,
    sms: 100,
    roamingIncluded: false,
    validityDays: 28,
    benefits: ['2GB data', '300 mins voice', 'Lowest-cost plan'],
    sourceOperatorRef: 'Vantage Saver Lite',
  },
  {
    _id: 'pl_essential_199',
    planName: 'Essential 199',
    operator: 'orbit',
    clusterIds: ['cl_budget_light', 'cl_talk_first'],
    price: 199,
    dataGB: 3,
    callMinutes: 600,
    sms: 200,
    roamingIncluded: false,
    validityDays: 28,
    benefits: ['3GB data', '600 mins voice', '200 SMS'],
    sourceOperatorRef: 'Orbit Essential 199',
  },
  {
    _id: 'pl_family_share',
    planName: 'Family Share 60',
    operator: 'nimbus',
    clusterIds: ['cl_balanced', 'cl_talk_first'],
    price: 1199,
    dataGB: 60,
    callMinutes: 2500,
    sms: 500,
    roamingIncluded: false,
    validityDays: 30,
    benefits: ['60GB shared across 4 lines', '2500 mins pooled', 'Family locator add-on'],
    sourceOperatorRef: 'Nimbus Family 60',
  },
  {
    _id: 'pl_night_owl',
    planName: 'Night Owl Data',
    operator: 'pulse',
    clusterIds: ['cl_heavy_streamer', 'cl_budget_light'],
    price: 249,
    dataGB: 12,
    callMinutes: 200,
    sms: 50,
    roamingIncluded: false,
    validityDays: 28,
    benefits: ['12GB data', 'Free 12am–6am unlimited data', '200 mins'],
    sourceOperatorRef: 'Pulse Night Owl',
  },
];

export const demoCustomer = {
  _id: 'cust_demo_01',
  name: 'Aarav Mehta',
  phone: '+91 98xxxxxx21',
  tenureMonths: 18,
  contractType: 'postpaid',
  usage: {
    avgCallMin: 420,
    dataGB: 34,
    smsCount: 65,
    dayEveningNightSplit: { day: 0.5, evening: 0.35, night: 0.15 },
    roamingUsage: 2,
    internationalUsage: 0,
  },
  clusterId: 'cl_balanced',
  currentPlanId: 'pl_essential_199',
  monthlySpend: 649,
  createdAt: '2024-11-02T10:00:00.000Z',
};

export const demoRecommendationHistory = [
  {
    _id: 'rec_1',
    generatedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    source: 'chat_profile',
    recommendedPlans: [
      { planId: 'pl_allrounder', score: 0.91 },
      { planId: 'pl_everyday_smart', score: 0.84 },
      { planId: 'pl_streamer_pro', score: 0.78 },
    ],
  },
  {
    _id: 'rec_2',
    generatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    source: 'cluster',
    recommendedPlans: [
      { planId: 'pl_everyday_smart', score: 0.88 },
      { planId: 'pl_allrounder', score: 0.8 },
      { planId: 'pl_essential_199', score: 0.6 },
    ],
  },
  {
    _id: 'rec_3',
    generatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    source: 'cluster',
    recommendedPlans: [
      { planId: 'pl_essential_199', score: 0.7 },
      { planId: 'pl_connect_400', score: 0.66 },
      { planId: 'pl_saver_lite', score: 0.5 },
    ],
  },
];

export const demoAdminStats = {
  totalCustomers: 16640,
  totalPlans: demoPlans.length,
  totalClusters: demoClusters.length,
  recommendationsGenerated30d: 8420,
  avgMatchScore: 82,
  lastClusteringRun: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
  lastBatchJobStatus: 'success',
};

export const demoKnowledgeSnippets = [
  { operatorName: 'Nimbus Mobile', planName: 'Nimbus Unlimited Data 75', note: 'Reference plan used to price Streamer Max' },
  { operatorName: 'Orbit Telecom', planName: 'Orbit Roam Easy', note: 'Reference plan used to price Roam Easy' },
];
