import { Sparkles, Wifi, PhoneCall, Wallet, Globe2 } from 'lucide-react';
import { Drawer } from '@/components/ui/Drawer';
import { Badge, Divider } from '@/components/ui/Primitives';
import { MatchScoreBreakdown } from './MatchScoreBreakdown';
import { operatorName } from './PlanCard';
import { currency } from '@/lib/format';

export function WhyThisPlanDrawer({ entry, open, onClose }) {
  if (!entry) return null;
  const { plan, matchPercent, breakdown, explanation } = entry;

  return (
    <Drawer open={open} onClose={onClose} subtitle="Why this plan?" title={plan.planName}>
      <div className="flex items-center gap-3 mb-6">
        <Badge tone="green">{matchPercent}% match</Badge>
        <span className="text-sm text-base-400">{operatorName(plan.operator)} · {currency(plan.price)}/mo</span>
      </div>

      <div className="rounded-xl border border-cyan-400/25 bg-cyan-400/[0.06] p-4 flex gap-3 mb-6">
        <Sparkles className="h-5 w-5 text-cyan-300 shrink-0 mt-0.5" />
        <p className="text-sm text-base-200 leading-relaxed">{explanation}</p>
      </div>

      <h3 className="text-sm font-semibold text-base-100 mb-3">Match score breakdown</h3>
      <MatchScoreBreakdown breakdown={breakdown} />

      <Divider className="my-6" />

      <h3 className="text-sm font-semibold text-base-100 mb-3">What's driving this recommendation</h3>
      <ul className="space-y-3">
        <ReasonRow icon={Wifi} label="Data allowance" value={`${plan.dataGB}GB vs. your typical usage`} />
        <ReasonRow icon={PhoneCall} label="Calling minutes" value={`${plan.callMinutes} mins included`} />
        <ReasonRow icon={Wallet} label="Monthly price" value={`${currency(plan.price)} against your budget`} />
        <ReasonRow icon={Globe2} label="Roaming" value={plan.roamingIncluded ? 'Included, matching your travel needs' : 'Not included — you rarely roam'} />
      </ul>

      <Divider className="my-6" />
      <p className="text-xs text-base-500 leading-relaxed">
        This explanation is grounded in your profile and real reference plans retrieved by the recommendation
        engine. Scores are generated by the backend's weighted-fit model; nothing here overrides that logic.
      </p>
    </Drawer>
  );
}

function ReasonRow({ icon: Icon, label, value }) {
  return (
    <li className="flex items-start gap-3">
      <span className="h-8 w-8 rounded-lg bg-base-800 flex items-center justify-center text-base-300 shrink-0">
        <Icon className="h-4 w-4" />
      </span>
      <div>
        <p className="text-xs text-base-400">{label}</p>
        <p className="text-sm text-base-100">{value}</p>
      </div>
    </li>
  );
}
